apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapRoles: |
    - rolearn: arn:aws:iam::399782975904:role/UdacityCapStone-workers-NodeInstanceRole-NZD6HHG6M90K
      username: system:node:ip-172-31-14-147.eu-west-3.compute.internal
      groups:
        - system:bootstrappers
        - system:nodes
        
  mapUsers: |
    - userarn: arn:aws:iam::399782975904:user/CilcleCi
      username: CilcleCi
      groups:
        - system:masters