version: 2.1

orbs:
  aws-eks: circleci/aws-eks@0.2.3
  kubernetes: circleci/kubernetes@0.4.0
  
executors:
  docker-publisher:
    environment:
      IMAGE_NAME: jonathancardoso/building-on-ci
    docker:
      - image: circleci/buildpack-deps:stretch
      
jobs:
  lint-backend:
    docker:
      - image: python:3.7.3-stretch
    steps:
      - checkout
      - run:
          name: Back-end lint
          command: |
            make all
            
  build-image:
    executor: docker-publisher
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: build-image
          command: |
            ./run_docker.sh
      - persist_to_workspace:
          root: .
          paths:
            - ./image.tar      
  push-image:
    executor: docker-publisher
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - checkout
      - setup_remote_docker
      - run:
          name: Load archived Docker image
          command: docker load -i /tmp/workspace/image.tar
      - run:
          name: push-image
          command: |
            ./upload_docker.sh

            
  K8S-Deploy:
    executor: aws-eks/python3
    steps:
      - checkout
      - kubernetes/install
      - aws-eks/update-kubeconfig-with-authenticator:
          cluster-name: UdacityCapStone-Cluster
      - kubernetes/create-or-update-resource:
          resource-file-path: k8s/deployment.yml
          resource-name: deployment/capstone-sample-app
      - kubernetes/create-or-update-resource:
          resource-file-path: k8s/service.yml
          resource-name: service/capstone-sample-app
            
  verify-deploy:
    docker:
      - image: python:3.7.3-stretch
    steps:
      - checkout
      - run:
          name: verify-deploy
          command: |
             curl a4ad9f157f2284cb89ad592a8a54669d-381491820.eu-west-3.elb.amazonaws.com | grep -q ${CIRCLE_SHA1}

          
workflows:
  default:
    jobs:
      - lint-backend
      - build-image:
          requires: [lint-backend]
      - push-image:
          requires: [build-image]
      - K8S-Deploy:
          requires: [push-image] 
      - aws-eks/update-container-image:
          cluster-name: UdacityCapStone-Cluster
          container-image-updates: "capstone-sample-app=daoudm/mock-api:${CIRCLE_SHA1}"
          resource-name: deployment/capstone-sample-app
          record: true
          requires: [K8S-Deploy] 
      - verify-deploy:
          requires: [aws-eks/update-container-image] 

