version: 2.1

jobs:
  lint-backend:
    docker:
      - image: python:3.7.3-stretch
    steps:
      - checkout
      - run:
          name: Back-end lint
          command: |
            make
            
  build-image:
    machine: true
    steps:
      - checkout
      - run:
          name: build-image
          command: |
            ./run_docker.sh

workflows:
  default:
    jobs:
      - lint-backend
      - build-image:
          requires: [lint-backend]
       
